version: "3.9"

services:
    mysql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        command: --authentication_policy=mysql_native_password --tls-version=
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${LOCAL_PASSWORD:-test}
            DB_NAME: ${dbName:-db_test}
        container_name: db
    # server:
    #     image: server
    #     restart: always
    #     build:
    #         context: .
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - mysql
